### ISSUE TITLE
Repeat groups

### ISSUE THREAD

**Issue by russianramblings** [iahmedani/kobo-wdc#2]
Hi, sorry if I'm doing this wrong, my first time posting to github. First thanks for the great WDC, very useful. I have used it with Tableau, works amazing. One issue: it doesn't seem to pull information on the repeats? I.e. when downloading a file from Kobo Toolbox I see a sheet for the main form information and (x) excel sheets for each repeat. When connecting with the WDC to Tableau I only see the main sheet. Is there a way to fix this ?

**Comment by iahmedani** [comment]
Hi dear, welcome to the amazing world of open source. 
I haven't worked on on repeats, and whenever I find time will try to update accordingly.
